// movies
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

// Fetch movie
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";

export const SEARCH_MOVIE = "SEARCH_MOVIE";

export const SET_PAGE_COUNT = "SET_PAGE_COUNT";
export const SET_OFFSET = "SET_OFFSET";
export const SET_PARTIAL_MOVIES = "SET_PARTIAL_MOVIES";
